# Generated by Django 4.2.5 on 2023-09-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
